baseURL = "https://surfclips.tv"
languageCode = "en-US"
title = "Surf Clips TV"
theme = "surfclips"

[params]
  description = "The best surf clips from around the world. Weekly Top 10 countdowns, Shorts, and full edits."
  tagline = "The best surf clips from around the world"
  youtube_channel = "https://www.youtube.com/@SurfClipsTV"
  merch_url = "https://surf-clips-tv-shop.fourthwall.com/"
  instagram = "https://www.instagram.com/surfclipstv/"
  tiktok = "https://www.tiktok.com/@surfclipstv"
  email_form_url = "https://script.google.com/macros/s/AKfycbykQXG11SrbHLaF6C81dbnB2RaBGOY597HttqvONjENyuS249ATVUX52zFzgoYsp41RxA/exec"

[taxonomies]
  tag = "tags"

[permalinks]
  clips = "/clips/:contentbasename/"

[sitemap]
  changefreq = "daily"
  priority = 0.7
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
